/**
 * Shared Playwright fixtures for EX-Installer E2E tests.
 *
 * The `workspacePage` fixture (mock compile):
 *   1. Creates an isolated temp directory for Electron userData.
 *   2. Seeds mock myRoster.h, myTurnouts.h, and config.h files on disk.
 *   3. Writes a SavedConfiguration into the preferences JSON so the home
 *      screen shows a card that can be clicked to load the workspace.
 *   4. Launches Electron with --mock-device --mock-compile --skip-startup --test-data-dir=<tmp>.
 *   5. Navigates: home → workspace (by clicking the mock config card).
 *   6. Returns the Playwright Page for the workspace view.
 *
 * The `workspacePageNative` fixture omits --mock-compile so compile calls
 * hit the real arduino-cli toolchain. Use it for COMPILE_E2E=1 tests.
 */

import { test as base, expect } from '@playwright/test'
import { _electron as electron } from '@playwright/test'
import type { Page, ElectronApplication } from '@playwright/test'
import { mkdtempSync, mkdirSync, writeFileSync, rmSync } from 'fs'
import { join, resolve } from 'path'
import { tmpdir } from 'os'

// ── Mock file content ─────────────────────────────────────────────────────────

export const MOCK_ROSTER_H = [
    'ROSTER(3, "Thomas", "LIGHT/HORN/*WHISTLE/BELL")',
    'ROSTER(5, "Percy", "LIGHT/HORN")',
].join('\n')

export const MOCK_TURNOUTS_H = [
    'SERVO_TURNOUT(200, 25, 410, 205, Slow, "Main Line Junction")',
    'SERVO_TURNOUT(201, 26, 410, 205, Fast, "Yard Entry")',
].join('\n')

export const MOCK_CONFIG_H = [
    '// config.h — mock test configuration',
    '#define MAIN_DRIVER_MOTOR_SHIELD STANDARD_MOTOR_SHIELD',
].join('\n')

/** Properly-formatted config.h for visual editor round-trip tests */
export const MOCK_CONFIG_H_COMPLETE = [
    '// config.h - Generated by EX-Installer',
    '',
    '#define IP_PORT 2560',
    '#define SCROLLMODE 1',
    '',
    '#define MOTOR_SHIELD_TYPE STANDARD_MOTOR_SHIELD',
    '',
].join('\n')

/** IOExpander myConfig.h for visual editor tests */
export const MOCK_MYCONFIG_H = [
    '// myConfig.h - Generated by EX-Installer',
    '',
    '#define I2C_ADDRESS 0x65',
    '#define DIAG_CONFIG_DELAY 5',
    '',
].join('\n')

export const MOCK_SKETCH_INO = [
    '// CommandStation-EX.ino — minimal mock sketch',
    '#include "config.h"',
    '',
    'void setup() {}',
    'void loop() {}',
].join('\n') + '\n'

// Resolve Electron main entry relative to repo root (tests/e2e/ → ../../out/main/index.js)
const ELECTRON_MAIN = resolve(__dirname, '../../out/main/index.js')

// ── Fixture types ─────────────────────────────────────────────────────────────

interface WorkspaceFixtures {
    electronApp: ElectronApplication
    workspacePage: Page
    electronAppNative: ElectronApplication
    workspacePageNative: Page
    ioExpanderApp: ElectronApplication
    ioExpanderPage: Page
}

// ── Shared: seed temp dir + launch Electron ───────────────────────────────────

async function launchApp(mockCompile: boolean): Promise<{ app: ElectronApplication; testDataDir: string }> {
    const testDataDir = mkdtempSync(join(tmpdir(), 'ex-installer-e2e-'))

    const scratchPath = join(testDataDir, 'scratch', 'CommandStation-EX')
    mkdirSync(scratchPath, { recursive: true })
    writeFileSync(join(scratchPath, 'myRoster.h'), MOCK_ROSTER_H, 'utf-8')
    writeFileSync(join(scratchPath, 'myTurnouts.h'), MOCK_TURNOUTS_H, 'utf-8')
    writeFileSync(join(scratchPath, 'config.h'), MOCK_CONFIG_H, 'utf-8')
    writeFileSync(join(scratchPath, 'CommandStation-EX.ino'), MOCK_SKETCH_INO, 'utf-8')

    const prefsDir = join(testDataDir, 'preferences')
    mkdirSync(prefsDir, { recursive: true })
    const savedConfig = {
        id: 'e2e-test-config',
        name: 'E2E Test Layout',
        deviceName: 'Arduino Mega 2560',
        devicePort: '/dev/ttyACM1',
        deviceFqbn: 'arduino:avr:mega:cpu=atmega2560',
        product: 'ex_commandstation',
        productName: 'EX-CommandStation',
        version: 'v5.4.0-Prod',
        repoPath: join(testDataDir, 'scratch'),
        scratchPath,
        configFiles: [
            { name: 'config.h', content: MOCK_CONFIG_H },
            { name: 'myRoster.h', content: MOCK_ROSTER_H },
            { name: 'myTurnouts.h', content: MOCK_TURNOUTS_H },
        ],
        lastModified: new Date().toISOString(),
    }
    writeFileSync(
        join(prefsDir, 'ex-installer-preferences.json'),
        JSON.stringify({ savedConfigurations: [savedConfig] }, null, 2),
        'utf-8',
    )

    const args = [
        ELECTRON_MAIN,
        '--mock-device',
        ...(mockCompile ? ['--mock-compile'] : []),
        '--skip-startup',
        `--test-data-dir=${testDataDir}`,
        '--disable-gpu',
        '--no-sandbox',
        '--js-flags=--no-expose-wasm',
    ]

    const app = await electron.launch({ args, chromiumSandbox: false })
    return { app, testDataDir }
}

async function navigateToWorkspace(app: ElectronApplication): Promise<Page> {
    const page = await app.firstWindow()
    page.on('dialog', (dialog) => dialog.accept().catch(() => undefined))
    await page.waitForLoadState('domcontentloaded')
    await page.evaluate(() => {
        document.querySelectorAll('[id^="ej2-licensing"]').forEach(el => el.remove())
    }).catch(() => undefined)
    await expect(page.getByText('E2E Test Layout')).toBeVisible({ timeout: 15_000 })
    await page.getByText('E2E Test Layout').click()
    await expect(page.getByText('Roster', { exact: true })).toBeVisible({ timeout: 10_000 })
    return page
}

async function launchIOExpanderApp(): Promise<{ app: ElectronApplication; testDataDir: string }> {
    const testDataDir = mkdtempSync(join(tmpdir(), 'ex-installer-e2e-iox-'))

    const scratchPath = join(testDataDir, 'scratch', 'EX-IOExpander')
    mkdirSync(scratchPath, { recursive: true })
    writeFileSync(join(scratchPath, 'myConfig.h'), MOCK_MYCONFIG_H, 'utf-8')

    const prefsDir = join(testDataDir, 'preferences')
    mkdirSync(prefsDir, { recursive: true })
    const savedConfig = {
        id: 'e2e-iox-config',
        name: 'E2E Test Layout',
        deviceName: 'Arduino Nano',
        devicePort: '/dev/ttyUSB0',
        deviceFqbn: 'arduino:avr:nano:cpu=atmega328',
        product: 'ex_ioexpander',
        productName: 'EX-IOExpander',
        version: 'v0.6.0',
        repoPath: join(testDataDir, 'scratch'),
        scratchPath,
        configFiles: [
            { name: 'myConfig.h', content: MOCK_MYCONFIG_H },
        ],
        lastModified: new Date().toISOString(),
    }
    writeFileSync(
        join(prefsDir, 'ex-installer-preferences.json'),
        JSON.stringify({ savedConfigurations: [savedConfig] }, null, 2),
        'utf-8',
    )

    const args = [
        ELECTRON_MAIN,
        '--mock-device',
        '--mock-compile',
        '--skip-startup',
        `--test-data-dir=${testDataDir}`,
        '--disable-gpu',
        '--no-sandbox',
        '--js-flags=--no-expose-wasm',
    ]

    const app = await electron.launch({ args, chromiumSandbox: false })
    return { app, testDataDir }
}

// ── Shared test base with workspace fixtures ──────────────────────────────────

async function navigateToIOExpanderWorkspace(app: ElectronApplication): Promise<Page> {
    const page = await app.firstWindow()
    page.on('dialog', (dialog) => dialog.accept().catch(() => undefined))
    await page.waitForLoadState('domcontentloaded')
    await page.evaluate(() => {
        document.querySelectorAll('[id^="ej2-licensing"]').forEach(el => el.remove())
    }).catch(() => undefined)
    await expect(page.getByText('E2E Test Layout')).toBeVisible({ timeout: 15_000 })
    await page.getByText('E2E Test Layout').click()
    // IOExpander has no Roster; wait for the config file tab instead
    await expect(page.getByText('myConfig.h')).toBeVisible({ timeout: 10_000 })
    return page
}

export const test = base.extend<WorkspaceFixtures>({
    // eslint-disable-next-line no-empty-pattern
    electronApp: async ({ }, use) => {
        const { app, testDataDir } = await launchApp(true)
        await use(app)
        await app.close()
        rmSync(testDataDir, { recursive: true, force: true })
    },

    workspacePage: async ({ electronApp }, use) => {
        await use(await navigateToWorkspace(electronApp))
    },

    // ── Real-compiler variants (no --mock-compile) ────────────────────────────
    // eslint-disable-next-line no-empty-pattern
    electronAppNative: async ({ }, use) => {
        const { app, testDataDir } = await launchApp(false)
        await use(app)
        await app.close()
        rmSync(testDataDir, { recursive: true, force: true })
    },

    workspacePageNative: async ({ electronAppNative }, use) => {
        await use(await navigateToWorkspace(electronAppNative))
    },

    // ── IOExpander workspace ──────────────────────────────────────────────────
    // eslint-disable-next-line no-empty-pattern
    ioExpanderApp: async ({ }, use) => {
        const { app, testDataDir } = await launchIOExpanderApp()
        await use(app)
        await app.close()
        rmSync(testDataDir, { recursive: true, force: true })
    },

    ioExpanderPage: async ({ ioExpanderApp }, use) => {
        await use(await navigateToIOExpanderWorkspace(ioExpanderApp))
    },
})

export { expect }
