/**
 * EX-CommandStation config.h and myAutomation.h generators
 * Ported from ex_installer/ex_commandstation.py
 */

export interface CommandStationConfigOptions {
    motorDriver: string
    display: string
    enableWifi: boolean
    wifiMode: string // 'ap' | 'sta'
    wifiSsid: string
    wifiPassword: string
    wifiChannel: number
    trackAMode: string
    trackBMode: string
    trackALocoId: number
    trackBLocoId: number
    enablePowerOnStart: boolean
    disableEeprom: boolean
}

/**
 * Generate config.h content for EX-CommandStation
 */
export function generateCommandStationConfig(opts: CommandStationConfigOptions): string {
    const lines: string[] = [
        '// config.h - Generated by EX-Installer',
        '',
    ]

    // Motor driver
    lines.push(`#define MOTOR_SHIELD_TYPE ${opts.motorDriver}`)

    // Display
    if (opts.display !== 'NONE') {
        if (opts.display === 'OLED_128x32') {
            lines.push('#define OLED_DRIVER 128,32')
        } else if (opts.display === 'OLED_128x64') {
            lines.push('#define OLED_DRIVER 128,64')
        } else if (opts.display === 'LCD_16x2') {
            lines.push('#define LCD_DRIVER 0x27,16,2')
        } else if (opts.display === 'LCD_20x4') {
            lines.push('#define LCD_DRIVER 0x27,20,4')
        }
    }

    // WiFi
    if (opts.enableWifi) {
        lines.push('#define ENABLE_WIFI true')
        if (opts.wifiMode === 'ap') {
            lines.push('#define WIFI_SSID "Your network name"')
            if (opts.wifiPassword) {
                lines.push(`#define WIFI_PASSWORD "${opts.wifiPassword}"`)
            } else {
                lines.push('#define WIFI_PASSWORD "Your network passwd"')
            }
        } else {
            // Station mode
            if (opts.wifiSsid) {
                lines.push(`#define WIFI_SSID "${opts.wifiSsid}"`)
            }
            if (opts.wifiPassword) {
                lines.push(`#define WIFI_PASSWORD "${opts.wifiPassword}"`)
            }
        }
        lines.push(`#define WIFI_CHANNEL ${opts.wifiChannel}`)
    }

    // Disable EEPROM
    if (opts.disableEeprom) {
        lines.push('#define DISABLE_EEPROM')
    }

    lines.push('')
    return lines.join('\n') + '\n'
}

export interface MyAutomationOptions {
    enablePowerOnStart: boolean
    trackAMode: string
    trackBMode: string
    trackALocoId: number
    trackBLocoId: number
}

/**
 * Generate myAutomation.h content for EX-CommandStation
 */
export function generateMyAutomation(opts: MyAutomationOptions): string {
    const lines: string[] = [
        '// myAutomation.h - Generated by EX-Installer',
        '',
    ]

    const hasTrackManager = opts.trackAMode !== 'MAIN' || opts.trackBMode !== 'PROG'
    const needsAutostart = opts.enablePowerOnStart || hasTrackManager

    if (needsAutostart) {
        lines.push('AUTOSTART')

        if (opts.enablePowerOnStart) {
            lines.push('POWERON')
        }

        if (hasTrackManager) {
            // Track A
            if (opts.trackAMode.startsWith('DC')) {
                lines.push(`SETLOCO(${opts.trackALocoId}) SET_TRACK(A,${opts.trackAMode})`)
            } else {
                lines.push(`SET_TRACK(A,${opts.trackAMode})`)
            }

            // Track B
            if (opts.trackBMode.startsWith('DC')) {
                lines.push(`SETLOCO(${opts.trackBLocoId}) SET_TRACK(B,${opts.trackBMode})`)
            } else {
                lines.push(`SET_TRACK(B,${opts.trackBMode})`)
            }
        }

        lines.push('DONE')
        lines.push('')

        // Roster entries for DC tracks
        if (hasTrackManager) {
            if (opts.trackAMode.startsWith('DC')) {
                lines.push(`ROSTER(${opts.trackALocoId},"DC TRACK A","/* /")`)
            }
            if (opts.trackBMode.startsWith('DC')) {
                lines.push(`ROSTER(${opts.trackBLocoId},"DC TRACK B","/* /")`)
            }
        }
    }

    lines.push('')
    return lines.join('\n') + '\n'
}
