/**
 * EX-IOExpander myConfig.h generator
 * Ported from ex_installer/ex_ioexpander.py
 */

export interface IOExpanderConfigOptions {
    i2cAddress: number
    disablePullups: boolean
    testMode: string | null // 'ANALOGUE_TEST' | 'INPUT_TEST' | 'OUTPUT_TEST' | 'PULLUP_TEST' | null
}

/**
 * Generate myConfig.h content for EX-IOExpander
 */
export function generateIOExpanderConfig(opts: IOExpanderConfigOptions): string {
    const lines: string[] = [
        '// myConfig.h - Generated by EX-Installer',
        '',
    ]

    // I2C address (stored as decimal in the field, output as hex)
    lines.push(`#define I2C_ADDRESS 0x${opts.i2cAddress.toString(16).toUpperCase()}`)

    // Diagnostics config delay default
    lines.push('#define DIAG_CONFIG_DELAY 5')

    // Test mode
    if (opts.testMode) {
        lines.push(`#define TEST_MODE ${opts.testMode}`)
    }

    // Disable I2C pullups
    if (opts.disablePullups) {
        lines.push('#define DISABLE_I2C_PULLUPS')
    }

    lines.push('')
    return lines.join('\n') + '\n'
}
