/**
 * EX-Turntable config.h generator
 * Ported from ex_installer/ex_turntable.py
 */

export interface TurntableConfigOptions {
    i2cAddress: number
    mode: 'TURNTABLE' | 'TRAVERSER'
    sensorTesting: boolean
    homeSensorActiveState: 'LOW' | 'HIGH'
    limitSensorActiveState: 'LOW' | 'HIGH'
    relayActiveState: 'HIGH' | 'LOW'
    phaseSwitching: 'AUTO' | 'MANUAL'
    phaseSwitchAngle: number
    stepperDriver: string
    disableOutputsIdle: boolean
    maxSpeed: number
    acceleration: number
    gearingFactor: number
    invertDirection: boolean
    invertStep: boolean
    invertEnable: boolean
    forwardOnly: boolean
    reverseOnly: boolean
    ledFast: number
    ledSlow: number
    enableDebug: boolean
    sanitySteps: number | null
    homeSensitivity: number | null
    fullStepCount: number | null
    debounceDelay: number | null
}

/**
 * Generate config.h content for EX-Turntable
 */
export function generateTurntableConfig(opts: TurntableConfigOptions): string {
    const lines: string[] = [
        '// config.h - Generated by EX-Installer',
        '',
    ]

    // I2C address
    lines.push(`#define I2C_ADDRESS 0x${opts.i2cAddress.toString(16).toUpperCase()}`)

    // Mode
    lines.push(`#define TURNTABLE_EX_MODE ${opts.mode}`)

    // Sensor testing
    if (opts.sensorTesting) {
        lines.push('#define SENSOR_TESTING')
    } else {
        lines.push('// #define SENSOR_TESTING')
    }

    // Sensor active states
    lines.push(`#define HOME_SENSOR_ACTIVE_STATE ${opts.homeSensorActiveState}`)
    lines.push(`#define LIMIT_SENSOR_ACTIVE_STATE ${opts.limitSensorActiveState}`)

    // Relay
    lines.push(`#define RELAY_ACTIVE_STATE ${opts.relayActiveState}`)

    // Phase switching
    lines.push(`#define PHASE_SWITCHING ${opts.phaseSwitching}`)
    if (opts.phaseSwitching === 'AUTO') {
        lines.push(`#define PHASE_SWITCH_ANGLE ${opts.phaseSwitchAngle}`)
    }

    // Stepper driver
    lines.push(`#define STEPPER_DRIVER ${opts.stepperDriver}`)

    // Disable outputs when idle
    if (opts.disableOutputsIdle) {
        lines.push('#define DISABLE_OUTPUTS_IDLE')
    }

    // Speed & acceleration
    lines.push(`#define STEPPER_MAX_SPEED ${opts.maxSpeed}`)
    lines.push(`#define STEPPER_ACCELERATION ${opts.acceleration}`)

    // Gearing factor
    lines.push(`#define STEPPER_GEARING_FACTOR ${opts.gearingFactor}`)

    // Invert options
    if (opts.invertDirection) {
        lines.push('#define INVERT_DIRECTION')
    } else {
        lines.push('// #define INVERT_DIRECTION')
    }

    if (opts.invertStep) {
        lines.push('#define INVERT_STEP')
    } else {
        lines.push('// #define INVERT_STEP')
    }

    if (opts.invertEnable) {
        lines.push('#define INVERT_ENABLE')
    } else {
        lines.push('// #define INVERT_ENABLE')
    }

    // Rotation direction
    if (opts.forwardOnly) {
        lines.push('#define ROTATE_FORWARD_ONLY')
    } else {
        lines.push('// #define ROTATE_FORWARD_ONLY')
    }

    if (opts.reverseOnly) {
        lines.push('#define ROTATE_REVERSE_ONLY')
    } else {
        lines.push('// #define ROTATE_REVERSE_ONLY')
    }

    // LED timing
    lines.push(`#define LED_FAST ${opts.ledFast}`)
    lines.push(`#define LED_SLOW ${opts.ledSlow}`)

    // Debug
    if (opts.enableDebug) {
        lines.push('#define DEBUG')
    } else {
        lines.push('// #define DEBUG')
    }

    // Advanced optional values
    if (opts.sanitySteps != null) {
        lines.push(`#define SANITY_STEPS ${opts.sanitySteps}`)
    } else {
        lines.push('// #define SANITY_STEPS 10000')
    }

    if (opts.homeSensitivity != null) {
        lines.push(`#define HOME_SENSITIVITY ${opts.homeSensitivity}`)
    } else {
        lines.push('// #define HOME_SENSITIVITY 300')
    }

    if (opts.fullStepCount != null) {
        lines.push(`#define FULL_STEP_COUNT ${opts.fullStepCount}`)
    } else {
        lines.push('// #define FULL_STEP_COUNT 4096')
    }

    if (opts.debounceDelay != null) {
        lines.push(`#define DEBOUNCE_DELAY ${opts.debounceDelay}`)
    } else {
        lines.push('// #define DEBOUNCE_DELAY 10')
    }

    lines.push('')
    return lines.join('\n') + '\n'
}
