
import { describe, it, expect, beforeAll } from 'vitest'
import { execFile } from 'child_process'
import { promisify } from 'util'

import fs from 'fs/promises'
import os from 'os'
import path from 'path'

const execFileAsync = promisify(execFile)

const REPO = path.join(os.tmpdir(), 'ex-installer-test-sketch')
const FQBN = 'arduino:avr:mega'



// Helper to write config files and a minimal .ino file, ensuring directory exists
async function writeSketchFiles(repoPath: string, configFiles: { name: string, content: string }[]) {
    await fs.mkdir(repoPath, { recursive: true })
    // Write config files
    for (const f of configFiles) {
        await fs.writeFile(`${repoPath}/${f.name}`, f.content)
    }
    // Write minimal .ino file
    const sketchName = path.basename(repoPath)
    const inoPath = path.join(repoPath, `${sketchName}.ino`)
    const inoContent = `void setup() {\n  // put your setup code here, to run once:\n}\n\nvoid loop() {\n  // put your main code here, to run repeatedly:\n}\n`;
    await fs.writeFile(inoPath, inoContent)
}

describe('Arduino CLI integration (node)', () => {
    const configFiles = [
        { name: 'config.h', content: `// config.h - Generated by EX-Installer v0.0.20 for EX-CommandStation v5.4.18-Prod\n\n#define IP_PORT 2560\n#define SCROLLMODE 1\n#define MOTOR_SHIELD_TYPE EXCSB1\n#define OLED_DRIVER 132,64\n#define WIFI_HOSTNAME \"dccex\"\n#define WIFI_SSID \"MySSID\"\n#define WIFI_PASSWORD \"MyPass\"\n#define ENABLE_WIFI true\n#define WIFI_CHANNEL 1\n#define DISABLE_EEPROM\n` },
    ]

    beforeAll(async () => {
        await writeSketchFiles(REPO, configFiles)
    })

    it('should compile the sketch using the real arduino-cli', async () => {
        const { stdout, stderr } = await execFileAsync('arduino-cli', [
            'compile',
            '--fqbn', FQBN,
            REPO
        ])
        expect(stdout + stderr).toMatch(/(Compiling|Sketch uses|Global variables|error:|✓|SUCCESS|FAILED)/)
    }, 30000)
})
