import { describe, it, expect, beforeAll, afterAll } from 'vitest'
import { execFile } from 'child_process'
import { promisify } from 'util'

import fs from 'fs/promises'
import os from 'os'
import path from 'path'

const execFileAsync = promisify(execFile)

// Source repo cloned by the app — must exist before running this test.
const SOURCE_REPO = path.join(os.homedir(), 'ex-installer', 'repos', 'CommandStation-EX')

// Scratch dir mirrors what the GUI creates: _build/<id>/CommandStation-EX
// The directory name MUST match the .ino filename (Arduino CLI requirement).
const SCRATCH_BASE = path.join(os.tmpdir(), 'ex-installer-test-build')
const REPO         = path.join(SCRATCH_BASE, 'CommandStation-EX')

// Arduino Mega on Prod branch — fully supported and compiles reliably.
// NOTE: ESP32-S3 / CSB1 support is split across two unmerged dev branches
//   (devel-csb1: has CSB1 motor driver, devel-s3: has S3 ADC register fix)
//   and cannot be compiled in isolation until those branches are merged.
const FQBN = 'arduino:avr:mega:cpu=atmega2560'

const MEGA_CONFIG_H = `\
// config.h - Generated by EX-Installer (integration test) for Arduino Mega

#define IP_PORT 2560
#define SCROLLMODE 1
#define MOTOR_SHIELD_TYPE STANDARD_MOTOR_SHIELD
#define WIFI_HOSTNAME "dccex"
#define DISABLE_EEPROM
`

/** Source-file extensions the GUI copies (excludes .example / .template). */
const ALLOWED_EXTS    = ['.ino', '.cpp', '.h']
const ALLOWED_SUBDIRS = ['src', 'libraries']

async function copySourceFiles(src: string, dest: string): Promise<void> {
    await fs.mkdir(dest, { recursive: true })
    const entries = await fs.readdir(src, { withFileTypes: true })
    for (const entry of entries) {
        const srcPath  = path.join(src,  entry.name)
        const destPath = path.join(dest, entry.name)
        if (entry.isDirectory() && ALLOWED_SUBDIRS.includes(entry.name)) {
            await copySourceFiles(srcPath, destPath)
        } else if (entry.isFile()) {
            const name = entry.name
            if (name.endsWith('.example') || name.endsWith('.template')) continue
            if (ALLOWED_EXTS.some(ext => name.endsWith(ext))) {
                await fs.copyFile(srcPath, destPath)
            }
        }
    }
}

describe('Arduino CLI integration — Mega (arduino:avr:mega)', () => {
    beforeAll(async () => {
        // Verify the source repo exists
        await fs.access(SOURCE_REPO)

        // Build scratch dir the same way the GUI does
        await fs.rm(SCRATCH_BASE, { recursive: true, force: true })
        await copySourceFiles(SOURCE_REPO, REPO)

        // Write the Mega config.h
        await fs.writeFile(path.join(REPO, 'config.h'), MEGA_CONFIG_H)
    })

    afterAll(async () => {
        await fs.rm(SCRATCH_BASE, { recursive: true, force: true })
    })

    it('should compile CommandStation-EX for Arduino Mega (arduino:avr:mega)', async () => {
        const { stdout, stderr } = await execFileAsync('arduino-cli', [
            'compile',
            '--fqbn', FQBN,
            '--output-dir', path.join(REPO, 'build'),
            REPO,
        ])
        expect(stdout + stderr).toMatch(/(Compiling|Sketch uses|Global variables|error:|✓|SUCCESS|FAILED)/)
    }, 120_000)
})
