import { app } from 'electron'
import { mkdir, writeFile } from 'fs/promises'
import { join } from 'path'
import type { SerialDeviceInfo } from '../../types/ipc'

/** True in `pnpm dev`; always false in a packaged app. */
export const IS_DEV_MOCK = !app.isPackaged

export const MOCK_SERIAL_PORTS: SerialDeviceInfo[] = [
    {
        // EX-CSB1 — ESP32-S3 with native USB (Espressif VID)
        path: 'MOCK_COM3',
        manufacturer: 'DCC-EX',
        serialNumber: 'DCCEX-CSB1-0001',
        vendorId: '303a',
        productId: '1001',
    },
    {
        // Arduino Mega 2560
        path: 'MOCK_COM4',
        manufacturer: 'Arduino (www.arduino.cc)',
        serialNumber: 'MOCK-MEGA-0001',
        vendorId: '2341',
        productId: '0042',
    },
    {
        // Arduino Uno
        path: 'MOCK_COM5',
        manufacturer: 'Arduino (www.arduino.cc)',
        serialNumber: 'MOCK-UNO-0001',
        vendorId: '2341',
        productId: '0043',
    },
]

export const MOCK_VERSIONS = [
    'v5.4.0-Prod',
    'v5.3.2-Prod',
    'v5.3.0-Prod',
    'v5.2.0-Prod',
    'v5.4.1-Devel',
    'v5.3.3-Devel',
]

export const MOCK_SKETCH_SEEDS: Record<string, { sketchFile: string; content: string }> = {
    // repoFolder → sketch
    'CommandStation-EX': {
        sketchFile: 'CommandStation-EX.ino',
        content: [
            '// CommandStation-EX.ino — minimal mock sketch for dev compilation',
            '#include "config.h"',
            '',
            'void setup() {}',
            'void loop() {}',
        ].join('\n') + '\n',
    },
    'EX-IOExpander': {
        sketchFile: 'EX-IOExpander.ino',
        content: [
            '// EX-IOExpander.ino — minimal mock sketch for dev compilation',
            '#include "myConfig.h"',
            '',
            'void setup() {}',
            'void loop() {}',
        ].join('\n') + '\n',
    },
    'EX-Turntable': {
        sketchFile: 'EX-Turntable.ino',
        content: [
            '// EX-Turntable.ino — minimal mock sketch for dev compilation',
            '#include "config.h"',
            '',
            'void setup() {}',
            'void loop() {}',
        ].join('\n') + '\n',
    },
}

/**
 * Default config file content seeded into the mock sketch directory.
 * - CommandStation-EX: minimal generated config matching what EX-Installer
 *   produces for an EX-CSB1 (EXCSB1 motor driver, WiFi AP mode, EEPROM disabled).
 * - EX-IOExpander / EX-Turntable: real myConfig.example.h / config.example.h
 *   content from the DCC-EX GitHub repos.
 */
export const MOCK_CONFIG_SEEDS: Record<string, Record<string, string>> = {
    'CommandStation-EX': {
        // config.h generated for EX-CSB1 (ESP32-S3, EXCSB1 motor driver, WiFi AP mode)
        // Matches output of generateCommandStationConfig() with CSB1 defaults:
        //   motorDriver: 'EXCSB1', display: 'OLED_132x64' (SH1106 onboard),
        //   enableWifi: true (auto for ESP32), wifiMode: 'ap',
        //   wifiHostname: 'dccex', wifiChannel: 1,
        //   disableEeprom: true (auto for ESP32)
        // NOTE: IP_PORT, SCROLLMODE, WIFI_HOSTNAME, and OLED_DRIVER are always-required —
        //       omitting any of them from a hand-edited config.h will cause a compile error.
        'config.h': `// config.h - Generated by EX-Installer

#define IP_PORT 2560
#define SCROLLMODE 1

#define MOTOR_SHIELD_TYPE EXCSB1
#define OLED_DRIVER 132,64
#define WIFI_HOSTNAME "dccex"
#define WIFI_SSID "Your network name"
#define WIFI_PASSWORD "Your network passwd"
#define ENABLE_WIFI true
#define WIFI_CHANNEL 1
#define DISABLE_EEPROM
`
    },
    'EX-IOExpander': {
        'myConfig.h': `/*
 *  © 2022 Peter Cole. All rights reserved.
 *
 *  This is the example configuration file for EX-IOExpander.
 * 
 *  It is highly recommended to copy this to "config.h" and modify to suit your specific
 *  requirements.
 * 
 *  NOTE: Modifications to this file will be overwritten by future software updates.
 */
#ifndef MYCONFIG_H
#define MYCONFIG_H

/////////////////////////////////////////////////////////////////////////////////////
//  Define I2C address
//  Default 0x90, can be any valid, available I2C address
// 
#define I2C_ADDRESS 0x65

/////////////////////////////////////////////////////////////////////////////////////
//  Uncomment to enable diag output
// 
// #define DIAG

/////////////////////////////////////////////////////////////////////////////////////
//  Delay between dumping the status of the port config if DIAG enabled
// 
#define DIAG_CONFIG_DELAY 5

/////////////////////////////////////////////////////////////////////////////////////
//  Enable test mode - ensure only one test mode is active at one time.
//  This is handy if serial input doesn't work for commands for some reason. 
// 
//  ANALOGUE - equivalent of <T A>
//  INPUT - equivalent of <T I>
//  OUTPUT - equivalent of <T O>
//  PULLUP - equivalent of <T P>
// 
// #define TEST_MODE ANALOGUE_TEST
// #define TEST_MODE INPUT_TEST
// #define TEST_MODE OUTPUT_TEST
// #define TEST_MODE PULLUP_TEST

/////////////////////////////////////////////////////////////////////////////////////
//  Uncomment to disable internal I2C pullup resistors
//  NOTE: This will not apply to all supported devices, refer to the documentation
// #define DISABLE_I2C_PULLUPS

#endif`,
    },
    'EX-Turntable': {
        'config.h': `/*
 *  © 2022 Peter Cole
 *
 *  This is the configuration file for Turntable-EX.
 */

/////////////////////////////////////////////////////////////////////////////////////
//  Define a valid (and free) I2C address, 0x60 is the default.
// 
#define I2C_ADDRESS 0x60

/////////////////////////////////////////////////////////////////////////////////////
//  Define the mode for Turntable-EX.
//  TURNTABLE : Use this for normal, 360 degree rotation turntables (Default).
//  TRAVERSER : Use this for vertical or horizontal traversers, or turntables that do
//              do not rotate a full 360 degrees.
// 
#define TURNTABLE_EX_MODE TURNTABLE
// #define TURNTABLE_EX_MODE TRAVERSER

/////////////////////////////////////////////////////////////////////////////////////
//  Enable sensor testing only, prevents all Turntable-EX operations.
//  Uncomment this line to disable all normal Turntable-EX operations in order to test
//  and validate that homing and limit sensors activate and deactivate correctly.
//  Note that you can enable sensor testing interactively in the serial console with <T>
// 
// #define SENSOR_TESTING

/////////////////////////////////////////////////////////////////////////////////////
//  Define the active state for the homing sensor.
//  LOW = When activated, the input is pulled down (ground or 0V).
//  HIGH = When activated, the input is pulled up (typically 5V).
// 
#define HOME_SENSOR_ACTIVE_STATE LOW

/////////////////////////////////////////////////////////////////////////////////////
//  REQUIRED FOR TRAVERSER MODE ONLY
//  Define the active state for the limit sensor.
//  LOW = When activated, the input is pulled down (ground or 0V).
//  HIGH = When activated, the input is pulled up (typically 5V).
// 
#define LIMIT_SENSOR_ACTIVE_STATE LOW

/////////////////////////////////////////////////////////////////////////////////////
//  Define the active state for the phase switching relays.
//  LOW = When activated, the input is pulled down (ground or 0V).
//  HIGH = When activated, the input is pulled up (typically 5V).
// 
#define RELAY_ACTIVE_STATE HIGH

/////////////////////////////////////////////////////////////////////////////////////
//  Define phase switching behaviour.
// 
//  PHASE_SWITCHING options:
//  AUTO    : When defined, phase will invert at PHASE_SWITCH_START_ANGLE, and revert
//            at PHASE_SWITCH_STOP_ANGLE (see below).
//  MANUAL  : When defined, phase will only invert using the Turn_PInvert command.
//  
//  Refer to the documentation for the full explanation on phase switching, and when
//  it is recommended to change these options.
// 
#define PHASE_SWITCHING AUTO
// #define PHASE_SWITCHING MANUAL

/////////////////////////////////////////////////////////////////////////////////////
//  Define automatic phase switching angle.
// 
//  If PHASE_SWITCHING is set to AUTO (see above), then when the turntable rotates
//  PHASE_SWITCH_ANGLE degrees from home, the phase will automatically invert.
//  Once the turntable reaches a further 180 degrees, the phase will automatically
//  revert.
// 
//  Refer to the documentation for the full explanation on phase switching, and how to
//  define the angle that's relevant for your layout.
// 
#define PHASE_SWITCH_ANGLE 45

/////////////////////////////////////////////////////////////////////////////////////
//  Define the stepper controller in use according to those available below, refer to the
//  documentation for further details on which to select for your application.
// 
//  ULN2003_HALF_CW   : ULN2003 in half step mode, clockwise
//  ULN2003_HALF_CCW  : ULN2003 in half step mode, counter clockwise
//  ULN2003_FULL_CW   : ULN2003 in full step mode, clockwise
//  ULN2003_FULL_CCW  : ULN2003 in full step mode, counter clockwise
//  A4988             : Two wire drivers (eg. A4988, DRV8825, TMC2208)
// 
//  NOTE: If you are using a different controller than those already defined, refer to
//  the documentation to define the appropriate configuration variables. Note there are
//  some controllers that are pin-compatible with an existing defined controller, and
//  in those instances, no custom configuration would be required.
// 

#define STEPPER_DRIVER ULN2003_HALF_CW
// #define STEPPER_DRIVER ULN2003_HALF_CCW
// #define STEPPER_DRIVER ULN2003_FULL_CW
// #define STEPPER_DRIVER ULN2003_FULL_CCW
// #define STEPPER_DRIVER A4988
// 
// When using a two wire driver (eg. A4988, DRV8825, TMC2208), it may be necessary to invert
// the direction pin. This is likely required when using a TMC2208. This has no effect on
// ULN2003.
// #define INVERT_DIRECTION
// 
// When using a two wire driver (eg. A4988, DRV8825, TMC2208), it may be necessary to invert
// the step pin. If so, uncomment this line. This has no effect on ULN2003.
// #define INVERT_STEP
// 
// When using a two wire driver (eg. A4988, DRV8825, TMC2208), it may be necessary to invert
// the enable pin behaviour if you wish to have the stepper driver disabled when not moving.
// This has no effect on ULN2003.
// #define INVERT_ENABLE

/////////////////////////////////////////////////////////////////////////////////////
//  Define the various stepper configuration items below if the defaults don't suit
//
//  Disable the stepper controller when idling, comment out to leave on. Note that this
//  is handy to prevent controllers overheating, so this is a recommended setting.
#define DISABLE_OUTPUTS_IDLE
// 
//  Define the acceleration and speed settings.
#define STEPPER_MAX_SPEED 200     // Maximum possible speed the stepper will reach
#define STEPPER_ACCELERATION 25   // Acceleration and deceleration rate
// 
// If using a gearing or microstep setup with larger than 32767 steps, you need to set the
// gearing factor appropriately.
// Step counts sent from EX-CommandStation will be multiplied by this number.
#define STEPPER_GEARING_FACTOR 1

/////////////////////////////////////////////////////////////////////////////////////
//  If dealing with steppers that have a lot of slop, it can be beneficial to force
//  rotating in one direction only. Enable one (and one only) of the below options if
//  a single rotation direction is required.
//  NOTE this does not apply in TRAVERSER mode.
//
//  #define ROTATE_FORWARD_ONLY
//  #define ROTATE_REVERSE_ONLY

/////////////////////////////////////////////////////////////////////////////////////
//  Define the LED blink rates for fast and slow blinking in milliseconds.
// 
//  The LED will alternative on/off for these durations.
#define LED_FAST 100
#define LED_SLOW 500

/////////////////////////////////////////////////////////////////////////////////////
//  ADVANCED OPTIONS
//  In normal circumstances, the settings below should not need to be adjusted unless
//  requested by support ticket, or if Tinkerers or Engineers are working with alternative
//  stepper drivers and motors.
// 
//  Enable debug outputs if required during troubleshooting.
//  Note you can enable debug output interactively in the serial console with <D>
// 
// #define DEBUG
// 
//  Define the maximum number of steps homing and calibration will perform before marking
//  these activities as failed. This step count must exceed a single full rotation in order
//  to be useful.
// #define SANITY_STEPS 10000
// 
//  Define the minimum number of steps the turntable needs to move before the homing sensor
//  deactivates, which is required during the calibration sequence. For high step count
//  setups, this may need to be increased.
// #define HOME_SENSITIVITY 300
// 
//  Override the step count determined by automatic calibration by uncommenting the line
//  below, and manually defining a specific step count.
// #define FULL_STEP_COUNT 4096
// 
//  Override the default debounce delay (in ms) if using mechanical home/limit switches that have
//  "noisy" switch bounce issues.
//  In TRAVERSER mode, default is 10ms as these would typically use mechanical switches.
//  In TURNTABLE mode, default is 0ms as these would typically use hall effect sensors.
// #define DEBOUNCE_DELAY 10
`,
    },
}

/**
 * Seeds the mock repo directory on disk so arduino-cli has a real sketch tree.
 * Called by the git:clone IPC handler when IS_DEV_MOCK is true.
 */
export async function seedMockRepo(dest: string): Promise<void> {
    await mkdir(dest, { recursive: true })
    const folderName = dest.split('/').pop() ?? ''
    const sketchSeed = MOCK_SKETCH_SEEDS[folderName]
    const configSeed = MOCK_CONFIG_SEEDS[folderName]
    if (sketchSeed) {
        await writeFile(join(dest, sketchSeed.sketchFile), sketchSeed.content, 'utf-8')
    }
    if (configSeed) {
        for (const [filename, content] of Object.entries(configSeed)) {
            await writeFile(join(dest, filename), content, 'utf-8')
        }
    }
}
