import { resolve } from 'aurelia'
import { Router } from '@aurelia/router'
import { IDialogService } from '@aurelia/dialog'
import { InstallerState } from '../models/installer-state'
import { PreferencesService } from '../services/preferences.service'
import { FileService } from '../services/file.service'
import { ToastService } from '../services/toast.service'
import { ArduinoCliService } from '../services/arduino-cli.service'
import { DevicePickerDialog } from '../components/device-picker-dialog'
import { DeviceWizard } from '../components/device-wizard'
import { hasGeneratorHeader } from '../utils/myAutomationParser'
import { parseDeviceFromHeader, injectDeviceHeader, reconcileDevicePort } from '../utils/configHeaderParser'
import { productDetails } from '../models/product-details'
import type { SavedConfiguration } from '../models/saved-configuration'
import type { ArduinoCliBoardInfo } from '../../../types/ipc'

/** File extensions we care about when scanning a loaded folder. */
const HEADER_EXTENSIONS = ['.h']

/** Known visual-editor files that may need migration if not generated by us. */
const MANAGED_FILES = new Set(['myRoster.h', 'myTurnouts.h'])

export class Home {
    private readonly router = resolve(Router)
    private readonly dialogService = resolve(IDialogService)
    readonly state = resolve(InstallerState)
    private readonly preferences = resolve(PreferencesService)
    private readonly files = resolve(FileService)
    private readonly toastService = resolve(ToastService)
    private readonly cli = resolve(ArduinoCliService)

    canLoad(): boolean | string {
        return this.state.cliReady ? true : 'startup'
    }

    async binding(): Promise<void> {
        await this.loadSavedConfigs()
    }

    private async loadSavedConfigs(): Promise<void> {
        try {
            const saved = await this.preferences.get('savedConfigurations') as SavedConfiguration[] | undefined
            this.state.savedConfigurations = Array.isArray(saved) ? saved : []
        } catch {
            this.state.savedConfigurations = []
        }
    }

    async openNewDevice(): Promise<void> {
        this.state.reset()
        const result = await this.dialogService
            .open({ component: () => DeviceWizard })
            .whenClosed((r) => r)
        if (typeof result === 'object' && result !== null && 'status' in result && (result as any).status === 'ok') {
            await this.router.load('workspace')
        }
    }

    async loadFromFolder(): Promise<void> {
        const folder = await this.files.selectDirectory()
        if (!folder) return

        // List all files in the selected directory
        const entries = await this.files.listDir(folder)
        const hFiles = entries.filter(e => HEADER_EXTENSIONS.some(ext => e.endsWith(ext)))

        // config.h is the minimum required marker of a valid DCC-EX config folder
        if (!hFiles.includes('config.h')) {
            this.toastService.show({
                title: 'Invalid Folder',
                content: 'The selected folder must contain at least a config.h file.',
                cssClass: 'e-toast-danger',
            })
            return
        }

        // Read every .h file and detect whether migration is needed
        const configFiles: Array<{ name: string; content: string }> = []
        let needsMigration = false

        for (const name of hFiles) {
            const content = await this.files.readFile(`${folder}/${name}`)
            configFiles.push({ name, content })
            if (MANAGED_FILES.has(name) && !hasGeneratorHeader(content)) {
                needsMigration = true
            }
        }

        // ── Device resolution ─────────────────────────────────────────────────
        // Check if config.h already contains a device header from a previous load.
        const configHFile = configFiles.find(f => f.name === 'config.h')!
        let device: ArduinoCliBoardInfo | null = parseDeviceFromHeader(configHFile.content)

        if (device) {
            // Board identity is known — silently reconcile the port in case the OS
            // assigned a different one since the last session (very common on Linux/Mac).
            try {
                const liveBoards = await this.cli.listBoards()
                const { device: reconciled, portChanged } = reconcileDevicePort(device, liveBoards)
                if (portChanged) {
                    // Update the in-memory config.h so the next Save persists the new port
                    configHFile.content = injectDeviceHeader(configHFile.content, reconciled)
                }
                device = reconciled
            } catch {
                // CLI not available (e.g. not installed yet) — fall back to stored port
            }
        } else {
            // No saved device in config.h — show the board picker so the user can
            // identify the board. The selection is written back into config.h so
            // subsequent opens skip this step.
            const result = await this.dialogService
                .open({ component: () => DevicePickerDialog })
                .whenClosed((r) => r)

            // 'cancel' = user dismissed the dialog entirely — abort folder load
            if ((result as any).status === 'cancel') return

            // 'ok' with null = user clicked "Continue without device"
            // 'ok' with board = user picked a board
            device = (result as any).value as ArduinoCliBoardInfo | null

            if (device) {
                // Embed device info as human-readable comments at the top of config.h.
                // On next open the header is parsed and the wizard is skipped.
                configHFile.content = injectDeviceHeader(configHFile.content, device)
            }
        }

        const selectedDevice: ArduinoCliBoardInfo = device ?? {
            name: 'Unknown',
            port: '',
            fqbn: '',
            protocol: 'serial',
        }

        // ── Sketch path resolution ────────────────────────────────────────────
        const { scratchPath, repoPath, productKey, sourceFolder } =
            await this.resolveSketchPath(folder, configFiles.map(f => f.name), entries)

        // Write user config files into the internal scratch directory so the
        // compiler can find them alongside the copied .ino and .cpp source files.
        if (sourceFolder) {
            for (const f of configFiles) {
                await this.files.writeFile(`${scratchPath}/${f.name}`, f.content)
            }
        }

        // ── Build SavedConfiguration ──────────────────────────────────────────
        const folderName = folder.split(/[\\/]/).filter(Boolean).pop() ?? folder

        const config: SavedConfiguration = {
            id: `folder-${Date.now()}`,
            name: folderName,
            deviceName: selectedDevice.name,
            devicePort: selectedDevice.port,
            deviceFqbn: selectedDevice.fqbn,
            product: productKey ?? '',
            productName: productKey ? (productDetails[productKey]?.productName ?? 'Loaded from Folder') : 'Loaded from Folder',
            version: '',
            repoPath: repoPath ?? folder,
            scratchPath,
            configFiles,
            lastModified: new Date().toISOString(),
            sourceFolder: sourceFolder ?? undefined,
        }

        // Replace any existing entry for the same folder, then persist
        const existing = Array.isArray(this.state.savedConfigurations)
            ? this.state.savedConfigurations : []
        this.state.savedConfigurations = [
            ...existing.filter(c => c.scratchPath !== scratchPath && c.sourceFolder !== folder),
            config,
        ]
        await this.preferences.set('savedConfigurations', this.state.savedConfigurations)

        // Populate InstallerState so the workspace can load
        this.state.selectedDevice = selectedDevice
        this.state.selectedProduct = config.product || null
        this.state.selectedVersion = config.version || null
        this.state.repoPath = config.repoPath
        this.state.scratchPath = scratchPath
        this.state.sourceFolder = sourceFolder
        this.state.configFiles = config.configFiles.map(f => ({ ...f }))
        this.state.activeConfigId = config.id

        if (needsMigration) {
            this.toastService.show({
                title: 'Files Imported',
                content: 'Some files were not created by EX-Installer. Review them in the editor — invalid lines will be highlighted.',
                cssClass: 'e-toast-warning',
            })
        }

        await this.router.load('workspace')
    }

    /**
     * Determines the sketch path to use for compilation after loading a folder.
     *
     * If the user's folder already contains a `.ino` file it is a complete Arduino
     * sketch and can be compiled directly.  Otherwise, we look for an installed
     * product repo in the app data directory, create a fresh internal scratch
     * directory under `repos/_build/<id>/<repoFolder>/`, copy the non-user source
     * files from the repo, and return that path so the compiler can find the `.ino`.
     *
     * Returns:
     *   scratchPath  — absolute path to compile from
     *   repoPath     — absolute path to the git source (null if none found / none needed)
     *   productKey   — matched product key (null if not detected)
     *   sourceFolder — the original user folder (non-null only when scratchPath !== folder,
     *                  i.e. an internal scratch was created and we must write config files
     *                  back to the user's folder on Save)
     */
    private async resolveSketchPath(
        folder: string,
        configFileNames: string[],
        entries: string[],
    ): Promise<{
        scratchPath: string
        repoPath: string | null
        productKey: string | null
        sourceFolder: string | null
    }> {
        // Folder is already a complete Arduino sketch — use it directly.
        if (entries.some(e => e.endsWith('.ino'))) {
            return { scratchPath: folder, repoPath: null, productKey: null, sourceFolder: null }
        }

        // Try to find a matching installed product repo and set up an internal scratch.
        try {
            const reposDir = await this.files.getInstallDir('repos')
            const configSet = new Set(configFileNames)

            for (const [productKey, product] of Object.entries(productDetails)) {
                const repoFolder = product.repoName.split('/')[1]
                const repoPath = `${reposDir}/${repoFolder}`
                const repoExists = await this.files.exists(`${repoPath}/.git`)
                if (!repoExists) continue

                // Product is a candidate only when all its minimum config files are
                // present in the user's folder (e.g. config.h for ex_commandstation).
                const hasMinFiles = product.minimumConfigFiles.every(f => configSet.has(f))
                if (!hasMinFiles) continue

                // Found a match — create a fresh internal scratch directory.
                const id = String(Date.now())
                const scratchPath = `${reposDir}/_build/${id}/${repoFolder}`

                try { await this.files.deleteFiles(scratchPath) } catch { /* ignore */ }
                await this.files.mkdir(scratchPath)

                // Selectively copy source files from the repo (no examples / templates,
                // no user-managed config files — those are overlaid separately).
                const allowedExts = ['.ino', '.cpp', '.h']
                const allowedSubDirs = ['src', 'libraries']
                const isSourceFile = (name: string): boolean =>
                    !name.endsWith('.example') &&
                    !name.endsWith('.template') &&
                    allowedExts.some(ext => name.endsWith(ext))

                const copySourceDir = async (srcDir: string, destDir: string): Promise<void> => {
                    const dirEntries = await this.files.listDir(srcDir)
                    for (const entry of dirEntries) {
                        if (allowedSubDirs.includes(entry)) {
                            await this.files.mkdir(`${destDir}/${entry}`)
                            await copySourceDir(`${srcDir}/${entry}`, `${destDir}/${entry}`)
                        } else if (isSourceFile(entry) && !configSet.has(entry)) {
                            await this.files.copyFiles(`${srcDir}/${entry}`, `${destDir}/${entry}`)
                        }
                    }
                }
                await copySourceDir(repoPath, scratchPath)

                return { scratchPath, repoPath, productKey, sourceFolder: folder }
            }
        } catch {
            // File system errors (repos dir doesn't exist, permissions, etc.) — fall through.
        }

        // No matching repo found — fall back to using the user's folder directly.
        // Compilation will fail if the folder lacks a .ino, but the user can still
        // edit and save their config files.
        return { scratchPath: folder, repoPath: null, productKey: null, sourceFolder: null }
    }

    async loadConfig(config: SavedConfiguration): Promise<void> {
        this.state.selectedDevice = {
            name: config.deviceName,
            port: config.devicePort,
            fqbn: config.deviceFqbn,
            protocol: 'serial',
        }
        this.state.selectedProduct = config.product || null
        this.state.selectedVersion = config.version || null
        this.state.repoPath = config.repoPath
        this.state.scratchPath = config.scratchPath
        this.state.sourceFolder = config.sourceFolder ?? null
        this.state.configFiles = config.configFiles.map((f) => ({ ...f }))
        this.state.activeConfigId = config.id
        await this.router.load('workspace')
    }

    async deleteConfig(config: SavedConfiguration, event: Event): Promise<void> {
        event.stopPropagation()
        this.state.savedConfigurations = this.state.savedConfigurations.filter((c) => c.id !== config.id)
        await this.preferences.set('savedConfigurations', this.state.savedConfigurations)
    }

    formatDate(iso: string): string {
        try {
            return new Date(iso).toLocaleDateString(undefined, { year: 'numeric', month: 'short', day: 'numeric' })
        } catch {
            return iso
        }
    }
}
